version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: payment
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

  payment-api:
    build: .
    depends_on:
      - postgres
      - kafka
    ports:
      - "8080:8080"